### ISSUE TITLE
Support BrainTree payment with Nonce

### ISSUE THREAD

**Issue by cnapagoda** [wso2-extensions/esb-connector-braintree#5]
**Description:**

Currently, create payment operation doesn't support nonce based payments[1]

[1].https://developers.braintreepayments.com/reference/general/testing/java#payment-method-nonces

**Suggested Labels:**

enhancement 

**Suggested Assignees:**

**Affected Product Version:**
1.0.1, 1.0.0
**OS, DB, other environment details and versions:**    

**Steps to reproduce:**

**Related Issues:**

**Comment by anupama-pathirage** [comment]
Moved the issue to https://github.com/wso2/micro-integrator/issues/3470
